from typing import Any

def main() -> None: ...
def bpe(data: Any, model: Any, vocab_size: Any, coverage: Any, n_threads: Any, pad_id: Any, unk_id: Any, bos_id: Any, eos_id: Any) -> None: ...
def encode(model: Any, output_type: Any, n_threads: Any, bos: Any, eos: Any, reverse: Any, stream: Any, dropout_prob: Any) -> None: ...
def validate_ignore_ids(ctx: Any, param: Any, value: Any): ...
def decode(model: Any, ignore_ids: Any) -> None: ...
def vocab(model: Any, verbose: Any) -> None: ...
